{% set name = "feedstockrot" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/axiom-data-science/feedstockrot/archive/{{ version }}.tar.gz
  sha256: 009e8e907d2cc139bf1b2d6c52d52175570dfb30a393a5a9cd7b15e040dff85b

build:
  number: 1004
  noarch: python
  entry_points:
    - feedstockrot=feedstockrot.command_line:main_run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - requests
    - packaging
    - pygithub
    - pyyaml
    - jinja2

test:
  imports:
    - feedstockrot
    - feedstockrot.package_sources
  commands:
    - pip check
    - feedstockrot --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/axiom-data-science/feedstockrot
  license: MIT
  license_file: LICENSE
  summary: Tool to check how rotten conda-forge feedstocks are

extra:
  recipe-maintainers:
    - kwilcox
