{% set name = "feedstockrot" %}
{% set version = "1.1.0" %}
{% set build = 1000 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: feedstockrot-{{ version }}.tar.gz
  url: https://github.com/axiom-data-science/feedstockrot/archive/{{ version }}.tar.gz
  sha256: 009e8e907d2cc139bf1b2d6c52d52175570dfb30a393a5a9cd7b15e040dff85b

build:
  skip: true  # [py<35]
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - feedstockrot = feedstockrot.command_line:main_run

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - requests
    - packaging
    - pygithub
    - pyyaml
    - jinja2

test:
  imports:
    - feedstockrot
    - feedstockrot.tests
  commands:
    - feedstockrot --help

about:
  home: https://github.com/axiom-data-science/feedstockrot
  license: MIT
  summary: Tool to check how rotten conda-forge feedstocks are

extra:
  recipe-maintainers:
    - kwilcox
