appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kQJYyiGpM9veagoqD9a4B7zmzGlAq708SLAJvMdPkucgFOgIE7bb1Zi7oCU1p/XpQz4/cl4AHiP0J5rGqCEt6IOx6BTf4mnBBmQuqdut95XPervIwPQDMZmhgYVF+rRlSNCaY+evKR0/TxCdCwqz9eX4/NGJWzc7ir14SsUinp9RfJSThleecJHjD/0cDzG963CYedeiwty9j2U1sVJGLgPWb9OhcRaNUI8bi3nQuzBHgwn9rhRz+YOsEDae+ipajNy8yxVmFhIRpNXVk8dw9HQXyLTkEWzmApclPNcyVIC4p2Da7bO6djZYFNoU9ChmEGOBMuEFD8hK3zuZrROCl0CTtJ2FWJBz/T68wEL9GrQvovxTy2CGNtvLtM2tQik65tPz1YrtjJ+kPVpEYrbPAOuufQSWt6BFhacOAxTfZXFx6BXdUmSJFA59aEbDdpqVAfpgNLi0pNS9g26InZQ6DXEHKwxlrjaK2bke+oldcR7IVVQ3zkrhviEFKBTxhR4XSbTzvSWpW9keKqpeG2YNDnPFPlvF9erO5XG9SbmiH8NuuypV92jhWshUUjUOfNzNnfWngdtE/kwAnoU+VS2NL0z+jAQN7v8o6OKZrqJ7ZQV6ZQu0iUKeBi6kt0LgPRxzwbLqyD3dNwPVYfOmW3oISIHQXeStlM8ozSkltnlhV5A=}
