travis:
  secure:
    BINSTAR_TOKEN: KfwcnozFyUQ2pUlWxlXadIJyBaDlXprn4AhQRo7I4ZCxZSvjcy13y/rqKyKB5Jbow/1EeE0DXrFApFvArcuQqFJTbJQCYmAGGxzBVj4VxpnDwSXOErsG8hTB+SFO0zjXlvTSKq0K2UWfXTBxtXDnxScgyAzu0raXiXCQz2kMQ7/2l9h8jgB41nBDpKDX8etJHwpb+MsP+dVq4Okk+2Vwvrj/vP/zqsk0LiQnaK2jaxNYh9NAsJCoWGGhzLoLCfZr2DmNWuotqtaRnHk8UKiY4LRshhDGhckIDCVzBDwNoXfEuVNGPIXeenuH0+OvxZEE5QUm0C6HNktQqCbBg+pV9SVObdYYY8Bs5C3UVT4hsJ+NfAXqBlcYP84NFspkQUWHtbGI50JM/QY7/aITp8vAa6m+DVs3ug4+slBZgPOTVosmVjIm0ELzaurpKsS+Q4N1AGsyd6PLfJ2g2ZoZAezg9ozy9j5HbuJcmUL5oBAKkw5LpUJxFcXgj14FnEb7gf1MXkxtsOYCmfsvm1/ngqC1m1BtRzQk7128yB3Hrx8Y1bf9x3Ycn4IE5dqUlbrlrBqdwV4Xy36moL3BOxwZsslBoQKD1317TOQ8xX3bPyuce3ONwBafoX8JZBWwgudbzLgm5+vjfy+51AnIllcyGmN4KXyO4pDNAh7xMcf/TSvcIfs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
